elixir: {
  shape: image
  icon: https://www.svgrepo.com/show/373577/elixir.svg
}

fun1: {
  shape: image
  icon: https://www.svgrepo.com/show/373577/elixir.svg
}

fun2: {
  shape: image
  icon: https://raw.githubusercontent.com/carlogilmar/svg-examples/cb4321d779673d0adc57b72474e16d1677df5a0d/label.svg
}

erlang: {
  icon: https://www.svgrepo.com/show/373586/erlang.svg
}

erlang -> elixir
erlang -> fun1
erlang -> fun2
