# https://www.svgrepo.com/collection/vscode-icons/

explanation: |md
  # MyElixirModule functions
  Context to generate the navigation Chart 
|

erlang: {
  shape: image
  icon: https://www.svgrepo.com/show/373586/erlang.svg
}

grid-columns: 3
c1
c2
c3
c4
c5
erlang
